# Generated by Django 5.1.3 on 2024-11-20 18:18

from django.db import migrations

def load_initial_data(apps, schema_editor):
    model = apps.get_model('api', 'Author')
    model.objects.create(name="Guy de Maupassant", birth_date="1893-08-05")
    model.objects.create(name="Johann Wolfgang von Goethe", birth_date="1749-08-28")
    model.objects.create(name="Jack London", birth_date="1876-01-12")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_name'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
